
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module LinkFPGA(

	//////////// LED //////////
	output		     [8:0]		LEDG,
	output		    [17:0]		LEDR,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// SW //////////
	input 		    [17:0]		SW,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,
	output		     [6:0]		HEX6,
	output		     [6:0]		HEX7
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

wire [7:0] pc_disp, rs1_disp, rs2_disp;


//=======================================================
//  Structural coding
//=======================================================
RISC_V RISC_V(
    .clk(~KEY[0]), 
    .reset(~KEY[3]),
	 .saidaPC(pc_disp),
	 .saida_rr1(LEDG[4:0]), 
	 .saida_rr2(LEDR[17:13]),
	 .saida_rs1(rs1_disp), 
	 .saida_rs2(rs2_disp)
);

display display1_pc(
    .entrada(pc_disp[3:0]),
    .seg(HEX0)
);

display display2_pc(
	 .entrada(pc_disp[7:4]),
	 .seg(HEX1)
);

display display1_rs1(
	 .entrada(rs1_disp[3:0]),
	 .seg(HEX4)
);
display display2_rs1(
	 .entrada(rs1_disp[7:4]),
	 .seg(HEX5)
);
display display1_rs2(
	 .entrada(rs2_disp[3:0]),
	 .seg(HEX6)
);
display display2_rs2(
	 .entrada(rs2_disp[7:4]),
	 .seg(HEX7)
);
endmodule